-- 04_demo_queries_and_crud_examples.sql
SET SQL_SAFE_UPDATES = 0;
USE auto_parts_ecommerce;

-- =========================================================
-- A) VIEWS (JOIN + SUBQUERY are required)
-- =========================================================

-- Suppress warnings for initial drops
SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0;
DROP VIEW IF EXISTS vw_part_catalog;
SET SQL_NOTES=@OLD_SQL_NOTES;
CREATE VIEW vw_part_catalog AS
SELECT
    p.part_id,
    p.part_name,
    p.part_number,
    p.unit_price,
    p.stock_quantity,
    p.part_status,
    pc.category_name,
    s.seller_id,
    s.store_name,
    s.specialization,
    -- SUBQUERY: avg rating per part
    (
        SELECT ROUND(AVG(r.rating), 2)
        FROM reviews r
        WHERE r.part_id = p.part_id
    ) AS avg_part_rating,
    -- SUBQUERY: review count per part
    (
        SELECT COUNT(*)
        FROM reviews r2
        WHERE r2.part_id = p.part_id
    ) AS review_count
FROM parts p
JOIN part_categories pc ON p.category_id = pc.category_id
JOIN sellers s ON p.seller_id = s.seller_id;

SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0;
DROP VIEW IF EXISTS vw_customer_summary;
SET SQL_NOTES=@OLD_SQL_NOTES;
CREATE VIEW vw_customer_summary AS
SELECT
    u.user_id,
    CONCAT(u.first_name, ' ', u.last_name) AS customer_name,
    u.email,
    COUNT(DISTINCT cv.vehicle_id) AS vehicle_count,
    -- SUBQUERY: last order date
    (
        SELECT MAX(o.order_date)
        FROM orders o
        WHERE o.user_id = u.user_id
    ) AS last_order_date,
    -- SUBQUERY: total spent excluding cancelled
    (
        SELECT COALESCE(SUM(o2.final_amount), 0)
        FROM orders o2
        WHERE o2.user_id = u.user_id
          AND o2.order_status <> 'cancelled'
    ) AS total_spent
FROM users u
LEFT JOIN customer_vehicles cv ON u.user_id = cv.user_id
WHERE u.user_type = 'customer'
GROUP BY u.user_id, u.first_name, u.last_name, u.email;

-- =========================================================
-- B) FUNCTION + PROCEDURES + CURSOR
-- =========================================================

SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0;
DROP FUNCTION IF EXISTS fn_cart_total;
SET SQL_NOTES=@OLD_SQL_NOTES;
DELIMITER $$
CREATE FUNCTION fn_cart_total(p_cart_id INT)
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
    DECLARE v_total DECIMAL(10,2);
    SELECT COALESCE(SUM(ci.quantity * ci.unit_price_snapshot), 0)
    INTO v_total
    FROM cart_items ci
    WHERE ci.cart_id = p_cart_id;
    RETURN v_total;
END$$
DELIMITER ;

SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0;
DROP PROCEDURE IF EXISTS sp_create_cart_for_user;
SET SQL_NOTES=@OLD_SQL_NOTES;
DELIMITER $$
CREATE PROCEDURE sp_create_cart_for_user(IN p_user_id INT, OUT p_cart_id INT)
BEGIN
    INSERT INTO carts (user_id, cart_status) VALUES (p_user_id, 'active');
    SET p_cart_id = LAST_INSERT_ID();
END$$
DELIMITER ;

-- Checkout procedure:
-- - Uses CURSOR to iterate through cart_items
-- - Inserts into orders + order_items
-- - Updates cart status
SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0;
DROP PROCEDURE IF EXISTS sp_checkout_cart;
SET SQL_NOTES=@OLD_SQL_NOTES;
DELIMITER $$
CREATE PROCEDURE sp_checkout_cart(IN p_cart_id INT, OUT p_order_id INT)
BEGIN
    DECLARE done INT DEFAULT 0;
    DECLARE v_user_id INT;
    DECLARE v_part_id INT;
    DECLARE v_qty INT;
    DECLARE v_unit_price DECIMAL(10,2);
    DECLARE v_seller_id INT;
    DECLARE v_total DECIMAL(10,2);

    DECLARE cur CURSOR FOR
        SELECT ci.part_id, ci.quantity, ci.unit_price_snapshot, p.seller_id
        FROM cart_items ci
        JOIN parts p ON ci.part_id = p.part_id
        WHERE ci.cart_id = p_cart_id;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;

    -- cart owner
    SELECT user_id INTO v_user_id FROM carts WHERE cart_id = p_cart_id;

    -- create order (order_number generated by trigger if NULL/empty)
    SET v_total = fn_cart_total(p_cart_id);

    INSERT INTO orders (order_number, user_id, total_amount, final_amount, order_status)
    VALUES (NULL, v_user_id, v_total, v_total, 'pending');

    SET p_order_id = LAST_INSERT_ID();

    OPEN cur;
    read_loop: LOOP
        FETCH cur INTO v_part_id, v_qty, v_unit_price, v_seller_id;
        IF done = 1 THEN
            LEAVE read_loop;
        END IF;

        INSERT INTO order_items (order_id, part_id, seller_id, quantity, unit_price, item_total)
        VALUES (p_order_id, v_part_id, v_seller_id, v_qty, v_unit_price, v_qty * v_unit_price);
        -- stock will be updated by trigger update_stock_after_order
    END LOOP;
    CLOSE cur;

    UPDATE carts SET cart_status = 'checked_out' WHERE cart_id = p_cart_id;
END$$
DELIMITER ;

-- =========================================================
-- C) QUERIES (examples)
-- =========================================================

-- 1) Part catalog (from VIEW)
SELECT '1) Part Catalog' AS Report_Name, v.* FROM vw_part_catalog v ORDER BY unit_price ASC LIMIT 20;

-- 2) Customer summary (from VIEW)
SELECT '2) Customer Summary' AS Report_Name, v.* FROM vw_customer_summary v ORDER BY total_spent DESC LIMIT 20;

-- 3) Compatible parts query (JOIN heavy)
SELECT 
    '3) Compatible Parts' AS Report_Name,
    p.part_id,
    p.part_name,
    p.part_number,
    p.unit_price,
    p.stock_quantity,
    s.store_name,
    vb.brand_name,
    vm.model_name,
    c.year_from,
    c.year_to
FROM parts p
JOIN sellers s ON p.seller_id = s.seller_id
JOIN compatibility c ON p.part_id = c.part_id
JOIN vehicle_brands vb ON c.brand_id = vb.brand_id
JOIN vehicle_models vm ON c.model_id = vm.model_id
WHERE vb.brand_name = 'Toyota'
  AND vm.model_name = 'Corolla'
  AND p.part_status = 'active'
  AND p.stock_quantity > 0
ORDER BY p.unit_price ASC;

-- 4) Top-selling parts (last 30 days) (JOIN + GROUP BY)
SELECT 
    '4) Top Selling Parts' AS Report_Name,
    p.part_id,
    p.part_name,
    SUM(oi.quantity) AS units_sold_30d,
    SUM(oi.item_total) AS revenue_30d
FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
JOIN parts p ON oi.part_id = p.part_id
WHERE o.order_status <> 'cancelled'
  AND o.order_date >= DATE_SUB(CURDATE(), INTERVAL 30 DAY)
GROUP BY p.part_id, p.part_name
ORDER BY revenue_30d DESC;

-- 5) Slow-moving parts (fixed: aggregate conditions must be in HAVING)
SELECT 
    '5) Slow Moving Parts' AS Report_Name,
    p.part_id,
    p.part_name,
    p.stock_quantity,
    MAX(o.order_date) AS last_sale_date,
    DATEDIFF(CURDATE(), MAX(o.order_date)) AS days_since_last_sale,
    COUNT(oi.order_item_id) AS total_sales_rows,
    COALESCE(SUM(oi.quantity), 0) AS total_units_sold
FROM parts p
LEFT JOIN order_items oi ON p.part_id = oi.part_id
LEFT JOIN orders o ON oi.order_id = o.order_id AND o.order_status <> 'cancelled'
WHERE p.part_status = 'active'
GROUP BY p.part_id, p.part_name, p.stock_quantity
HAVING (last_sale_date IS NULL OR DATEDIFF(CURDATE(), last_sale_date) > 90)
ORDER BY days_since_last_sale DESC;

-- =========================================================
-- D) SCENARIO: INPUT DATA + TRIGGERS + CRUD (+ "BEFORE/AFTER" SELECTS)
-- =========================================================

-- Step D1) Insert a brand new customer
INSERT INTO users (email, password_hash, first_name, last_name, phone, user_type, account_status)
VALUES ('demo.customer@example.com', SHA2('DemoPass123!', 256), 'Demo', 'Customer', '+905550001111', 'customer', 'active');

SET @demo_user_id = LAST_INSERT_ID();

-- Step D2) Insert a customer vehicle (validated by trigger in 02_triggers_fixed.sql)
INSERT INTO customer_vehicles (user_id, make, model, year, engine_type, license_plate, is_default)
VALUES (@demo_user_id, 'Toyota', 'Corolla', 2023, '1.6 Petrol', '34DEMO123', TRUE);

SET @demo_vehicle_id = LAST_INSERT_ID();

-- Step D3) Create a cart for that customer (procedure)
CALL sp_create_cart_for_user(@demo_user_id, @demo_cart_id);

-- Step D4) "BEFORE" snapshot: stock before cart insert
SELECT 'D4) Stock Before Cart' AS Step, part_id, part_name, stock_quantity, unit_price, part_status
FROM parts
WHERE part_number IN ('TOY-OIL-001', 'TOY-BPAD-010');

-- Step D5) Add 2 items to cart (trigger captures unit_price_snapshot + validates stock)
INSERT INTO cart_items (cart_id, part_id, quantity, unit_price_snapshot, vehicle_id)
SELECT @demo_cart_id, p.part_id, 2, p.unit_price, @demo_vehicle_id
FROM parts p
WHERE p.part_number = 'TOY-OIL-001';

INSERT INTO cart_items (cart_id, part_id, quantity, unit_price_snapshot, vehicle_id)
SELECT @demo_cart_id, p.part_id, 1, p.unit_price, @demo_vehicle_id
FROM parts p
WHERE p.part_number = 'TOY-BPAD-010';

-- Step D6) "AFTER" snapshot: cart content (unit_price_snapshot must be set)
SELECT 'D6) Cart Content' AS Step, ci.cart_item_id, ci.cart_id, p.part_name, ci.quantity, ci.unit_price_snapshot
FROM cart_items ci
JOIN parts p ON ci.part_id = p.part_id
WHERE ci.cart_id = @demo_cart_id;

-- Step D7) Checkout the cart (procedure uses CURSOR + inserts order_items; trigger updates stock)
CALL sp_checkout_cart(@demo_cart_id, @demo_order_id);

-- Step D8) "AFTER" snapshot: order header + items
SELECT 'D8) Order Header' AS Step, order_id, order_number, user_id, total_amount, final_amount, order_status, order_date
FROM orders
WHERE order_id = @demo_order_id;

SELECT 'D8) Order Items' AS Step, oi.order_item_id, oi.order_id, p.part_name, oi.quantity, oi.unit_price, oi.item_total
FROM order_items oi
JOIN parts p ON oi.part_id = p.part_id
WHERE oi.order_id = @demo_order_id;

-- Step D9) "AFTER" snapshot: stock after checkout (should be reduced by order_items trigger)
SELECT 'D9) Stock After Checkout' AS Step, part_id, part_name, stock_quantity, part_status
FROM parts
WHERE part_number IN ('TOY-OIL-001', 'TOY-BPAD-010');

-- Step D10) Payment insert
INSERT INTO payments (order_id, payment_method, amount, status, transaction_id)
VALUES (@demo_order_id, 'credit_card', (SELECT final_amount FROM orders WHERE order_id=@demo_order_id), 'completed', CONCAT('TXN-', UUID()));

-- Step D11) UPDATE example: move order status to processing
SELECT 'D11) Order Status Before' AS Step, order_id, order_status FROM orders WHERE order_id=@demo_order_id; -- BEFORE
UPDATE orders SET order_status = 'processing' WHERE order_id = @demo_order_id;
SELECT 'D11) Order Status After' AS Step, order_id, order_status FROM orders WHERE order_id=@demo_order_id; -- AFTER

-- Step D12) DELETE example: remove 1 cart item (create a new cart with 2 items to demo partial delete)
CALL sp_create_cart_for_user(@demo_user_id, @demo_cart2_id);

INSERT INTO cart_items (cart_id, part_id, quantity, unit_price_snapshot, vehicle_id)
SELECT @demo_cart2_id, p.part_id, 1, p.unit_price, @demo_vehicle_id
FROM parts p
WHERE p.part_number = 'REN-CAB-050';

INSERT INTO cart_items (cart_id, part_id, quantity, unit_price_snapshot, vehicle_id)
SELECT @demo_cart2_id, p.part_id, 1, p.unit_price, @demo_vehicle_id
FROM parts p
WHERE p.part_number = 'TOY-OIL-001';

SELECT * FROM cart_items WHERE cart_id=@demo_cart2_id; -- BEFORE (2 items)
DELETE FROM cart_items WHERE cart_id=@demo_cart2_id AND part_id = (SELECT part_id FROM parts WHERE part_number='REN-CAB-050');
SELECT * FROM cart_items WHERE cart_id=@demo_cart2_id; -- AFTER (1 item remains)

-- Step D13) ALTER TABLE / ADD / MODIFY examples
-- ADD a new column
ALTER TABLE parts ADD COLUMN weight_kg DECIMAL(6,2) NULL AFTER unit_price;

-- MODIFY a column type/size (example: increase part_number length)
ALTER TABLE parts MODIFY COLUMN part_number VARCHAR(120);

-- Update some rows for the new column
UPDATE parts SET weight_kg = 0.35 WHERE part_number = 'TOY-OIL-001';
UPDATE parts SET weight_kg = 1.80 WHERE part_number = 'TOY-BDSK-020';

SELECT part_id, part_name, part_number, unit_price, weight_kg FROM parts WHERE part_number IN ('TOY-OIL-001','TOY-BDSK-020');

-- Step D14) Trigger demo: cancel order -> restore stock (restore_stock_on_order_cancellation)
SELECT 'D14) Stock Before Cancel' AS Step, part_id, part_name, stock_quantity FROM parts WHERE part_number IN ('TOY-OIL-001','TOY-BPAD-010'); -- BEFORE
UPDATE orders SET order_status = 'cancelled' WHERE order_id = @demo_order_id;
SELECT 'D14) Stock After Cancel' AS Step, part_id, part_name, stock_quantity FROM parts WHERE part_number IN ('TOY-OIL-001','TOY-BPAD-010'); -- AFTER (restored)

-- Step D15) Archive demo (requires archive_orders table from schema_fixed)
-- We archive a specific delivered order older than 1 year to avoid impacting seeded rows and to avoid FK errors.
SET @cutoff_date = DATE_SUB(CURDATE(), INTERVAL 1 YEAR);

-- CLEANUP first to allow re-runs without Duplicate Key Error
DELETE FROM payments WHERE order_id IN (SELECT order_id FROM orders WHERE order_number = 'ORD-2023-0999');
DELETE FROM order_items WHERE order_id IN (SELECT order_id FROM orders WHERE order_number = 'ORD-2023-0999');
DELETE FROM orders WHERE order_number = 'ORD-2023-0999';
DELETE FROM archive_orders WHERE order_number = 'ORD-2023-0999';

-- Create one delivered order older than 1 year
INSERT INTO orders (order_number, user_id, total_amount, final_amount, order_status, order_date)
VALUES ('ORD-2023-0999', 6, 100.00, 100.00, 'delivered', DATE_SUB(CURDATE(), INTERVAL 400 DAY));
SET @old_order_id = LAST_INSERT_ID();

-- Add a payment row for this archived order (to demonstrate FK-safe delete order)
INSERT INTO payments (order_id, payment_method, amount, status, transaction_id)
VALUES (@old_order_id, 'credit_card', 100.00, 'completed', CONCAT('TXN-', UUID()));


-- BEFORE: counts
SELECT 'D15) Archive Count Before' AS Step, COUNT(*) AS orders_total_before FROM orders;
SELECT 'D15) Archive Count Before' AS Step, COUNT(*) AS archive_total_before FROM archive_orders;
-- BEFORE: snapshot (row exists in orders, not in archive)
SELECT 'D15) Target Order Before' AS Step, o.* FROM orders o WHERE order_id = @old_order_id;
SELECT 'D15) Archive Content Before' AS Step, ao.* FROM archive_orders ao; 

-- Archive (insert with explicit column list)
INSERT INTO archive_orders (order_id, order_number, user_id, total_amount, final_amount, order_status, order_date)
SELECT o.order_id, o.order_number, o.user_id, o.total_amount, o.final_amount, o.order_status, o.order_date
FROM orders o
WHERE o.order_id = @old_order_id
  AND o.order_status = 'delivered'
  AND o.order_date < @cutoff_date;

-- Delete child rows first to satisfy FK constraints
DELETE FROM payments WHERE order_id = @old_order_id;
DELETE FROM order_items WHERE order_id = @old_order_id;

-- Then delete the archived order
DELETE FROM orders WHERE order_id = @old_order_id;

-- AFTER: snapshot (order removed from orders, exists in archive)
-- We select 1 row from orders to show it's gone (or remaining table data) and the specific archived row + seed
SELECT 'D15) Orders Table Post-Delete' AS Step, o.* FROM orders o WHERE order_id = @old_order_id UNION ALL SELECT 'D15) Orders Table Top 1' AS Step, o.* FROM orders o LIMIT 1; 
SELECT 'D15) Archive Table Result' AS Step, ao.* FROM archive_orders ao WHERE order_id = @old_order_id OR order_id = 1001;

-- AFTER: counts
SELECT 'D15) Orders Count After' AS Step, COUNT(*) AS orders_total_after FROM orders;
SELECT 'D15) Archive Count After' AS Step, COUNT(*) AS archive_total_after FROM archive_orders;
SET SQL_SAFE_UPDATES = 1;
